#spring.application.name=user-center
##zookeeper 连接地址
##如果使用了spring cloud zookeeper config这个配置应该配置在 bootstrap.yml/bootstrap.properties中
#spring.cloud.zookeeper.connect-string=192.168.109.200:2181
##将本服务注册到zookeeper，如果不希望自己被发现可以配置为false, 默认为 true
#spring.cloud.zookeeper.discovery.register=true

#配置微服务名称
spring:
  application:
    name: user-center

#配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.214.1:8848

ribbon:
  eager-load:
    # 开启ribbon饥饿加载
    enabled: true
    # 配置mall-user使用ribbon饥饿加载，多个使用逗号分隔
    clients: producter-center

#logging:
#  level:
#    com.example.usercenter.feign: debug

#暴露actuator端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

#feign:
#  client:
#    config:
#      producter-center:  #\u5BF9\u5E94\u5FAE\u670D\u52A1
#        loggerLevel: FULL


feign:
  # 配置 GZIP 来压缩数据
  compression:
    request:
      enabled: true
      # 配置压缩的类型
      mime-types: text/xml,application/xml,application/json
      # 最小压缩值
      min-request-size: 2048
    response:
      enabled: true
server:
  port: 9999