server:
  port: 8889

#服务名称
spring:
  application:
    name: producter-center

  #Nacos server地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.214.1:8848


#\u66B4\u9732actuator\u7AEF\u70B9
management:
  endpoints:
    web:
      exposure:
        include: '*'

