#spring.application.name=user-center
##zookeeper \u8FDE\u63A5\u5730\u5740 \uFF0C
##\u5982\u679C\u4F7F\u7528\u4E86 spring cloud zookeeper config\u8FD9\u4E2A\u914D\u7F6E\u5E94\u8BE5\u914D\u7F6E\u5728 bootstrap.yml/bootstrap.properties\u4E2D
#spring.cloud.zookeeper.connect-string=192.168.109.200:2181
##\u5C06\u672C\u670D\u52A1\u6CE8\u518C\u5230zookeeper\uFF0C\u5982\u679C\u4E0D\u5E0C\u671B\u81EA\u5DF1\u88AB\u53D1\u73B0\u53EF\u4EE5\u914D\u7F6E\u4E3Afalse, \u9ED8\u8BA4\u4E3A true
#spring.cloud.zookeeper.discovery.register=true

#\u914D\u7F6E\u5FAE\u670D\u52A1\u540D\u79F0
spring:
  application:
    name: user-center

  #\u914D\u7F6Enacos\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.214.1:8848

ribbon:
  eager-load:
    # \u5F00\u542Fribbon\u9965\u997F\u52A0\u8F7D
    enabled: true
    # \u914D\u7F6Emall-user\u4F7F\u7528ribbon\u9965\u997F\u52A0\u8F7D\uFF0C\u591A\u4E2A\u4F7F\u7528\u9017\u53F7\u5206\u9694
    clients: producter-center

#logging:
#  level:
#    com.example.usercenter.feign: debug

#\u66B4\u9732actuator\u7AEF\u70B9
management:
  endpoints:
    web:
      exposure:
        include: '*'

#feign:
#  client:
#    config:
#      producter-center:  #\u5BF9\u5E94\u5FAE\u670D\u52A1
#        loggerLevel: FULL


feign:
  # \u914D\u7F6E GZIP \u6765\u538B\u7F29\u6570\u636E
  compression:
    request:
      enabled: true
      # \u914D\u7F6E\u538B\u7F29\u7684\u7C7B\u578B
      mime-types: text/xml,application/xml,application/json
      # \u6700\u5C0F\u538B\u7F29\u503C
      min-request-size: 2048
    response:
      enabled: true